# Generated by Django 3.0.2 on 2020-04-02 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200331_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='images',
        ),
    ]
