# Generated by Django 3.0.2 on 2020-08-29 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200829_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_type',
        ),
    ]
