# Generated by Django 3.0.2 on 2020-08-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20200829_0247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='thumbnails',
            new_name='thumbnail',
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
