# Generated by Django 3.0.2 on 2020-08-30 17:30

import ckeditor.fields
from django.db import migrations
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('projects', '0011_auto_20200829_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='content',
            field=ckeditor.fields.RichTextField(
                blank=True,
                null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=taggit_autosuggest.managers.TaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='taggit.TaggedItem',
                to='taggit.Tag',
                verbose_name='Tags'),
        ),
    ]
