version: '3.7'

services:
    web:
        build:
            context: ./noahpanpizza
            dockerfile: Dockerfile.prod
        command: gunicorn noahpanpizza.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/home/app/web/static
            - media_volume:/home/app/web/media
        expose:
            - 8000
        env_file:
            - ./.env.prod
        extra_hosts:
            db: 172.104.10.73
        image: plloppii/web:latest
    nginx:
        build: ./nginx
        volumes:
            - static_volume:/home/app/web/static
            - media_volume:/home/app/web/media
        ports:
            - 1337:80
        depends_on:
            - web
        image: plloppii/nginx:latest
    # Use if dockerize database is necessary
    # db:
    #     image: postgres:12.0-alpine
    #     volumes:
    #         - postgres_data:/var/lib/postgresql/data/
    #     env_file:
    #         - ./.env.prod.db
volumes:
    static_volume:
    media_volume: