version: '3.7'

services:
    web:
        image: plloppii/web:latest
        build:
            context: ./noahpanpizza
            dockerfile: Dockerfile.prod
        command: gunicorn noahpanpizza.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/home/app/web/static
            - media_volume:/home/app/web/media
        expose:
            - 8000
        env_file:
            - ./.env.prod
        extra_hosts:
            db: 172.104.10.73
    nginx-proxy:
        image: plloppii/nginx-proxy:latest
        container_name: nginx-proxy
        ports:
            - 443:443
            - 80:80
        build: nginx
        restart: always
        volumes:
            - static_volume:/home/app/web/static
            - media_volume:/home/app/web/media
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - dhparam:/etc/nginx/dhparam
            - certs:/etc/nginx/certs:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro
        depends_on:
            - web
        network_mode: bridge 
    acme-companion:
        image: nginxproxy/acme-companion
        container_name: nginx-proxy-acme
        env_file:
            - .env.prod.proxy-companion
        volumes_from: 
            - nginx-proxy
        volumes:
            - certs:/etc/nginx/certs
            - acme:/etc/acme.sh
            - /var/run/docker.sock:/var/run/docker.sock:ro
        depends_on:
            - nginx-proxy
    # Use if dockerize database is necessary
    # db:
    #     image: postgres:12.0-alpine
    #     volumes:
    #         - postgres_data:/var/lib/postgresql/data/
    #     env_file:
    #         - ./.env.prod.db
volumes:
    static_volume:
    media_volume:
    vhost:
    html:
    dhparam:
    certs:
    acme: