# Generated by Django 3.0.2 on 2020-09-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_readtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='readtime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
