# Generated by Django 3.0.2 on 2020-09-09 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200908_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='quantity_instock',
        ),
    ]
