# Generated by Django 3.0.2 on 2020-09-10 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cartitem_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='item',
            new_name='product',
        ),
    ]
