# Generated by Django 3.0.2 on 2020-09-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20200912_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='city',
            field=models.CharField(default='NY', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='zipcode',
            field=models.CharField(max_length=5),
        ),
    ]
