# Generated by Django 3.0.2 on 2020-09-18 01:34

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20200913_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='user',
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='address1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='address2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='zipcode',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='cart',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.ContactInfo'),
        ),
    ]
