# Generated by Django 3.0.2 on 2020-09-19 03:06

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20200918_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='phone_number',
            field=models.CharField(default='6463307800', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='address1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='address2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='zipcode',
            field=models.CharField(max_length=5),
        ),
    ]
