# Generated by Django 3.0.2 on 2020-10-18 20:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20200919_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='paypal_information',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                null=True),
        ),
    ]
