# Generated by Django 3.0.2 on 2020-10-19 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_cart_paypal_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='ordered',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Cart'),
        ),
    ]
