# Generated by Django 3.0.2 on 2020-10-28 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20201019_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(
                blank=True,
                max_length=100,
                null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(
                blank=True,
                default='product/thumbnails/default.jpg',
                upload_to='product/thumbnails'),
        ),
    ]
