# Generated by Django 3.0.2 on 2020-11-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20201114_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10),
        ),
    ]
